only_if: $CIRRUS_BRANCH == 'main' && $CIRRUS_REPO_OWNER == 'anarazel'

env:
  GAC: ENCRYPTED[08c58c0a60e1b0dfd4748960cef61296508f85b81ea8a553ee06c9df86bb2398c3240b35bfd76196f3967819da15cd25]

task:
  container:
    dockerfile: LinuxPackerDockerfile
    cpu: 0.5
    memory: 256Mi
  env:
    GOOGLE_APPLICATION_CREDENTIALS: pg-vm-images-aio.json
    DEBIAN_FRONTEND: noninteractive

  init_script:
    - echo $GAC | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
    - gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
    - packer --version

  matrix:
    - name: freebsd-13-0
      env:
        PACKERFILE: googlecompute/freebsd.pkr.hcl

    - env:
        PACKERFILE: googlecompute/linux.pkr.hcl

      matrix:
        - name: bullseye
        - name: sid
        - name: sid-newkernel
        - name: sid-newkernel-uring

  build_image_script:
    - export DATE=$(date +'%Y-%m-%dt%H-%M')
    - set -x
    - packer build -only "*.${CIRRUS_TASK_NAME}" -timestamp-ui -force -var "image_date=$DATE" $PACKERFILE

    - gcloud compute images add-iam-policy-binding --project pg-vm-images-aio --member=allAuthenticatedUsers --role=roles/compute.imageUser pg-aio-${CIRRUS_TASK_NAME}-${DATE}
