only_if: $CIRRUS_BRANCH == 'main'
only_if: $CIRRUS_REPO_OWNER == 'anarazel'

env:
  GAC: ENCRYPTED[08c58c0a60e1b0dfd4748960cef61296508f85b81ea8a553ee06c9df86bb2398c3240b35bfd76196f3967819da15cd25]

task:
  container:
    dockerfile: LinuxPackerDockerfile
    cpu: 1
    memory: 1GB
  env:
    GOOGLE_APPLICATION_CREDENTIALS: pg-vm-images-aio.json
    DEBIAN_FRONTEND: noninteractive

  init_script:
    - echo $GAC | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
    - gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
    - packer --version

  matrix:
    - name: pg-aio-sid
    - name: pg-aio-sid-newkernel
    - name: pg-aio-bullseye
    - name: pg-aio-freebsd-12-2

  build_image_script:
    - export DATE=$(date +'%Y-%m-%dt%H-%M')
    - packer build -only ${CIRRUS_TASK_NAME} -timestamp-ui -force -var "image_date=$DATE" googlecompute/images.json
    - gcloud compute images create ${CIRRUS_TASK_NAME}-${DATE} --family ${CIRRUS_TASK_NAME} --source-image ${CIRRUS_TASK_NAME}-tmp-${DATE}
    - gcloud compute images add-iam-policy-binding --project pg-vm-images-aio --member=allAuthenticatedUsers --role=roles/compute.imageUser ${CIRRUS_TASK_NAME}-${DATE}
    - gcloud compute images delete -q ${CIRRUS_TASK_NAME}-tmp-${DATE}
