name: build PG CI Containers

on: [push, pull_request]

env:
  CONTAINER: linux_debian_ci
  CONTAINER_VARIANTS_JSON: '["sanity-check","linux-meson-32","linux-meson-64","linux-autoconf","compiler-warnings"]'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  # One job to determine dates etc, so it's the same between concurrently built images
  setup:
    name: Setup

    # If a PR within the repository, skip the run for the PR, because the push
    # already triggered CI.
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)

    runs-on: ubuntu-slim
    outputs:
      date: ${{ steps.setup.outputs.date}}
      tag_base: ${{ steps.setup.outputs.tag_base}}
      name_base: ${{ steps.setup.outputs.name_base}}
      tag_prefix: ${{ steps.setup.outputs.tag_base}}/${{ steps.setup.outputs.name_base}}

      variants_json: ${{ env.CONTAINER_VARIANTS_JSON }}
      variants_shell: ${{ steps.setup.outputs.variants_shell}}

    steps:
      - name: setup
        id: setup
        run: |
          echo date=$(date --utc +'%Y-%m-%dt%H-%M-%S') >> "$GITHUB_OUTPUT"

          # Include the branch name, due to that autmatically everything on a
          # non-main branch will only be used if somebody explicitly changes
          # the image name in the postgres repo.
          echo "tag_base=ghcr.io/${GITHUB_REPOSITORY}/${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"

          echo "name_base=$CONTAINER" >> "$GITHUB_OUTPUT"

          echo "variants_shell=$(echo "$CONTAINER_VARIANTS_JSON"|jq -r '.[]'|tr '\n' ' ')" >> "$GITHUB_OUTPUT"

  # Build Containers, but don't push them under an automatically usable label
  build-containers:
    name: Build Containers
    needs: setup
    if: |
      !cancelled() &&
      needs.setup.result == 'success'

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    env:
      DEBIAN_RELEASE: trixie
      DATE: ${{needs.setup.outputs.date}}

    steps:
      - name: info
        run: |
          env

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - uses: actions/checkout@v6

      - name: Setup Arg File
        run: |
          tee build-args.conf <<-EOF
            DEBIAN_RELEASE=${DEBIAN_RELEASE}
            DATE=${{needs.setup.outputs.date}}
            IMAGE_NAME=${{needs.setup.outputs.name_base}}/${DEBIAN_RELEASE}
          EOF

      - name: Build CI Containers
        run: |
          for variant in ${{needs.setup.outputs.variants_shell}}; do
            echo "::group::build_$variant"

            time podman image build \
              --build-arg-file=build-args.conf \
              --cache-ttl 8h \
              -f docker/linux_debian_ci \
              --tag ${{needs.setup.outputs.tag_prefix}}/${DEBIAN_RELEASE}/$variant:${{needs.setup.outputs.date}} \
              --target=$variant \
              . \
              2>&1

            echo ::endgroup::
          done

      - name: Show CI Containers
        run: |
          podman images

      - name: Inspect CI Containers
        run: |
          for variant in ${{needs.setup.outputs.variants_shell}}; do
            echo "::group::inspect_$variant"

            podman image inspect \
              ${{needs.setup.outputs.tag_prefix}}/${DEBIAN_RELEASE}/$variant:${{needs.setup.outputs.date}}

            echo ::endgroup::
          done

      - name: Push CI Containers
        run: |
          for variant in ${{needs.setup.outputs.variants_shell}}; do
            echo "::group::push_$variant"

            time podman image push \
              --compression-format=zstd --compression-level=10 \
              ${{needs.setup.outputs.tag_prefix}}/${DEBIAN_RELEASE}/$variant:${{needs.setup.outputs.date}} \
              2>&1
            echo ::endgroup::
          done


  # Basic test that the containers work
  test-containers:
    name: Test ${{matrix.variant}} for ${{matrix.debian_release}}
    needs: [setup, build-containers]
    if: |
      !cancelled() &&
      needs.build-containers.result == 'success'

    runs-on: ubuntu-latest

    strategy: &strategy
      fail-fast: false
      matrix:
        debian_release: [trixie]
        variant: ${{fromJSON(needs.setup.outputs.variants_json)}}

    container:
      image: ${{needs.setup.outputs.tag_prefix}}/${{matrix.debian_release}}/${{matrix.variant}}:${{needs.setup.outputs.date}}
      options: --privileged

    steps:

      # FIXME: Add more sanity tests
      - name: Basic test for ${{matrix.debian_release}} ${{matrix.variant}}
        run: |
          echo $IMAGE_NAME $IMAGE_DATE
          env


  # If the tests above pass, tag them as the latest
  tag-containers:
    name: Tag ${{matrix.variant}} for ${{matrix.debian_release}} as latest
    needs: [setup, test-containers]
    if: |
      !cancelled() &&
      needs.test-containers.result == 'success'

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    strategy: *strategy

    steps:

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull ${{matrix.debian_release}} ${{matrix.variant}}
        run: |
          set -x
          podman image pull \
            ${{needs.setup.outputs.tag_prefix}}/${{matrix.debian_release}}/${{matrix.variant}}:${{needs.setup.outputs.date}}

      - name: Tag ${{matrix.debian_release}} ${{matrix.variant}} as latest
        run: |
          set -x
          podman image tag \
            ${{needs.setup.outputs.tag_prefix}}/${{matrix.debian_release}}/${{matrix.variant}}:${{needs.setup.outputs.date}} \
            ${{needs.setup.outputs.tag_prefix}}/${{matrix.debian_release}}/${{matrix.variant}}:latest

      - name: Push ${{matrix.debian_release}} ${{matrix.variant}} as latest
        run: |
          set -x
          podman image push \
            --compression-format=zstd --compression-level=10 \
            ${{needs.setup.outputs.tag_prefix}}/${{matrix.debian_release}}/${{matrix.variant}}:latest


      # Backward compat aliases for the current CI name
      - name: Alias ${{matrix.debian_release}} ${{matrix.variant}} as as ci
        if: ${{ matrix.variant == 'linux-meson-32' }}
        run: |
          set -x
          podman tag \
            ${{needs.setup.outputs.tag_prefix}}/${{matrix.debian_release}}/${{matrix.variant}}:latest \
            ${{needs.setup.outputs.tag_base}}/linux_debian_${{matrix.debian_release}}_ci:latest

          podman image push \
            --compression-format=zstd --compression-level=10 \
            ${{needs.setup.outputs.tag_base}}/linux_debian_${{matrix.debian_release}}_ci:latest

      - name: Alias ${{matrix.debian_release}} ${{matrix.variant}} as as ci_docs
        if: ${{ matrix.variant == 'compiler-warnings' }}
        run: |
          set -x
          podman tag \
            ${{needs.setup.outputs.tag_prefix}}/${{matrix.debian_release}}/${{matrix.variant}}:latest \
            ${{needs.setup.outputs.tag_base}}/linux_debian_${{matrix.debian_release}}_ci_docs:latest

          podman image push \
            --compression-format=zstd --compression-level=10 \
            ${{needs.setup.outputs.tag_base}}/linux_debian_${{matrix.debian_release}}_ci_docs:latest
