name: build PG CI Containers

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  # One job to determine dates etc, so it's the same between concurrently built images
  setup:
    name: Setup
    runs-on: ubuntu-slim
    outputs:
      date: ${{ steps.setup.outputs.date}}
      tag_base: ${{ steps.setup.outputs.tag_base}}
      name_base: ${{ steps.setup.outputs.name_base}}
      tag_prefix: ${{ steps.setup.outputs.tag_base}}/${{ steps.setup.outputs.name_base}}

    steps:
      - name: setup
        id: setup
        run: |
          echo date=$(date --utc +'%Y-%m-%dt%H-%M-%S') >> "$GITHUB_OUTPUT"

          # Include the branch name, due to that autmatically everything on a
          # non-main branch will only be used if somebody explicitly changes
          # the image name in the postgres repo.
          echo tag_base=ghcr.io/${GITHUB_REPOSITORY}/${GITHUB_REF_NAME} >> "$GITHUB_OUTPUT"

          echo name_base=linux_debian >> "$GITHUB_OUTPUT"


  # Build Containers, but don't push them under an automatically usable label
  build-containers:
    name: Build Containers
    needs: setup
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    env:
      TAG_BASE: ghcr.io/anarazel/pg-vm-images/
      DEBIAN_RELEASE: trixie
      NAME_BASE: test_linux_debian
      DATE: ${{needs.setup.outputs.date}}
    steps:
      - name: info
        run: |
          env

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - uses: actions/checkout@v6

        #--tag ${{needs.setup.outputs.tag_prefix}}_${DEBIAN_RELEASE}_ci_docs:latest \
      - name: Build CI Base Container
        run: |
          set -x
          docker buildx build \
            --debug \
            --build-arg DEBIAN_RELEASE=${DEBIAN_RELEASE} \
            --build-arg DATE=${{needs.setup.outputs.date}} \
            --build-arg IMAGE_NAME=${{needs.setup.outputs.name_base}}_${DEBIAN_RELEASE}_ci \
            --build-arg TAG_PREFIX=${{needs.setup.outputs.tag_prefix}} \
            -f docker/linux_debian_ci \
            --tag ${{needs.setup.outputs.tag_prefix}}_${DEBIAN_RELEASE}_ci:${{needs.setup.outputs.date}} \
            .

      - name: Push CI Base Container
        run: |
          set -x
          docker push \
            ${{needs.setup.outputs.tag_prefix}}_${DEBIAN_RELEASE}_ci:${{needs.setup.outputs.date}}

      - name: Build CI Docs Container
        run: |
          docker buildx build \
            --build-arg DEBIAN_RELEASE=${DEBIAN_RELEASE} \
            --build-arg DATE=${{needs.setup.outputs.date}} \
            --build-arg IMAGE_NAME=${{needs.setup.outputs.name_base}}_${DEBIAN_RELEASE}_ci_docs \
            --build-arg TAG_PREFIX=${{needs.setup.outputs.tag_prefix}} \
            -f docker/linux_debian_ci_docs \
            --tag ${{needs.setup.outputs.tag_prefix}}_${DEBIAN_RELEASE}_ci_docs:${{needs.setup.outputs.date}} \
            .

      - name: Push CI Docs Container
        run: |
          set -x
          docker push \
            ${{needs.setup.outputs.tag_prefix}}_${DEBIAN_RELEASE}_ci_docs:${{needs.setup.outputs.date}}


  # Basic test that the containers work
  test-containers:
    name: Test Containers
    needs: [setup, build-containers]

    if: |
      !cancelled() &&
      needs.build-containers.result != 'failure'

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        debian_release: [trixie]
        image: [ci, ci_docs]

    container:
      image: ${{needs.setup.outputs.tag_prefix}}_${{matrix.debian_release}}_${{matrix.image}}:${{needs.setup.outputs.date}}
      options: --privileged

    steps:

      # FIXME: Add more sanity tests
      - name: Basic test for ${{matrix.debian_release}} ${{matrix.image}}
        run: |
          echo $IMAGE_NAME
          env


  # If the tests above pass, tag them as the latest
  tag-containers:
    name: Tag Containers as latest
    needs: [setup, test-containers]

    if: |
      !cancelled() &&
      needs.test-containers.result != 'failure'

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    # FIXME: Fix repetition
    strategy:
      fail-fast: false
      matrix:
        debian_release: [trixie]
        image: [ci, ci_docs]

    steps:

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull ${{matrix.debian_release}} ${{matrix.image}}
        run: |
          set -x
          docker pull \
            ${{needs.setup.outputs.tag_prefix}}_${{matrix.debian_release}}_${{matrix.image}}:${{needs.setup.outputs.date}}

      - name: Tag ${{matrix.debian_release}} ${{matrix.image}} as latest
        run: |
          set -x
          docker image tag \
            ${{needs.setup.outputs.tag_prefix}}_${{matrix.debian_release}}_${{matrix.image}}:${{needs.setup.outputs.date}} \
            ${{needs.setup.outputs.tag_prefix}}_${{matrix.debian_release}}_${{matrix.image}}:latest

      - name: Push ${{matrix.debian_release}} ${{matrix.image}} as latest
        run: |
          set -x
          docker image push \
            ${{needs.setup.outputs.tag_prefix}}_${{matrix.debian_release}}_${{matrix.image}}:latest
